#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb 19 17:51:30 2022

@author: go34660
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tables
import h5py

test = np.loadtxt('5167742.pbs/empty_1200_1500.txt',delimiter = ' ')
#%%
plt.plot(1/test[0],test[1]**2)

#plt.imshow(np.array(dataset1)**2, interpolation='spline36', cmap='coolwarm')
